# Generated by Django 5.1.4 on 2025-01-04 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_id_alter_passenger_id_alter_place_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
