from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("query/places/<str:q>", views.query, name="query"),
    path("flight", views.flight, name="flight"),
    path("review", views.review, name="review"),
    path("flight/ticket/book", views.book, name="book"),
    #path("flight/ticket/payment", views.payment, name="payment"),
    path('flight/ticket/api/<str:ref>', views.ticket_data, name="ticketdata"),
    #path('flight/ticket/print',views.get_ticket, name="getticket"),
    path('flight/map', views.map_view, name="map"),
    path('flight/post', views.list_posts, name="post"),
    path('flight/create_post', views.show_post, name="create_post"),
    path('flight/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('flight/guest_post/', views.guest_post, name='guest_post'),
    path('flight/pin_post/', views.pin_view, name='pin_view'),
    path('flight/chat', views.show_chat, name="chat"),
    path('flight/chat/messages/', views.get_messages, name="get_messages"),  
    path('flight/chat/send/', views.post_message, name="post_message"),
    #path('flight/bookings', views.bookings, name="bookings"),
    #path('flight/ticket/cancel', views.cancel_ticket, name="cancelticket"),
    #path('flight/ticket/resume', views.resume_booking, name="resumebooking"),
    path('contact', views.contact, name="contact"),
    path('privacy-policy', views.privacy_policy, name="privacypolicy"),
    path('terms-and-conditions', views.terms_and_conditions, name="termsandconditions"),
    path('about-us', views.about_us, name="aboutus"),
]